## Essential Python for Data Analysis

## Numpy

In [1]:
import numpy as np

my_arr=np.arange(1000000)
my_list=list(range(1000000))

%time for _ in range(10): my_arr2=my_arr*2

Wall time: 80 ms


In [2]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [6]:
data=np.random.randn(3, 4)
data

array([[-0.52659244, -1.04881292, -1.86518784,  0.62665205],
       [-0.99873418, -0.36430521, -2.57133083, -0.70149046],
       [ 0.21875021, -0.76825936, -1.84164716, -0.65907785]])

In [7]:
data*10

array([[ -5.26592444, -10.48812922, -18.6518784 ,   6.26652047],
       [ -9.98734181,  -3.64305213, -25.71330829,  -7.01490458],
       [  2.18750212,  -7.68259364, -18.41647161,  -6.5907785 ]])

In [8]:
data+data

array([[-1.05318489, -2.09762584, -3.73037568,  1.25330409],
       [-1.99746836, -0.72861043, -5.14266166, -1.40298092],
       [ 0.43750042, -1.53651873, -3.68329432, -1.3181557 ]])

In [9]:
data.shape

(3, 4)

In [10]:
data.dtype

dtype('float64')

In [14]:
data1=[6, 7.5, 8, 0, 1]
arr1=np.array(data1)
arr1
arr1.dtype

dtype('float64')

In [15]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.empty((2,3,2))

array([[[1.05318489, 2.09762584],
        [3.73037568, 1.25330409],
        [1.99746836, 0.72861043]],

       [[5.14266166, 1.40298092],
        [0.43750042, 1.53651873],
        [3.68329432, 1.3181557 ]]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
arr1=np.array([1,2,3], dtype=np.float64)

In [24]:
arr1.dtype

dtype('float64')

In [26]:
arr=np.array([1,2,3,4,5])
arr.dtype

float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [27]:
#Basic Indexing and Slicing 
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [33]:
arr_slice[1]=12345
arr #The mutations are reflected in the original array arr 

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [34]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [35]:
arr2d=np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0,2]

3

In [39]:
#Boolean Indexing
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data=np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [40]:
data

array([[ 0.88649617,  0.07928406, -2.70691694, -0.21545032],
       [ 0.49056932,  1.06218523,  1.9568737 , -1.81357511],
       [ 1.38871522,  0.96575554, -0.24859585,  0.09923088],
       [ 0.83547747, -0.95499431, -2.95206372,  0.16032963],
       [-0.30175687,  0.74213284, -0.61940401,  0.41748777],
       [-0.42356711, -0.16504942,  0.03722069, -0.66913455],
       [ 1.4294056 ,  0.39939736, -0.35438651, -0.90555486]])

In [41]:
names.dtype

dtype('<U4')

In [42]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [43]:
data[names=='Bob']

array([[ 0.88649617,  0.07928406, -2.70691694, -0.21545032],
       [ 0.83547747, -0.95499431, -2.95206372,  0.16032963]])

In [45]:
data[names=='Bob', 2:]

array([[-2.70691694, -0.21545032],
       [-2.95206372,  0.16032963]])

In [46]:
mask=(names=='Bob') | (names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [47]:
data[mask]

array([[ 0.88649617,  0.07928406, -2.70691694, -0.21545032],
       [ 1.38871522,  0.96575554, -0.24859585,  0.09923088],
       [ 0.83547747, -0.95499431, -2.95206372,  0.16032963],
       [-0.30175687,  0.74213284, -0.61940401,  0.41748777]])

In [48]:
# Set all negative values to 0
data[data<0]=0
data

array([[0.88649617, 0.07928406, 0.        , 0.        ],
       [0.49056932, 1.06218523, 1.9568737 , 0.        ],
       [1.38871522, 0.96575554, 0.        , 0.09923088],
       [0.83547747, 0.        , 0.        , 0.16032963],
       [0.        , 0.74213284, 0.        , 0.41748777],
       [0.        , 0.        , 0.03722069, 0.        ],
       [1.4294056 , 0.39939736, 0.        , 0.        ]])

In [49]:
#Setting whole rows or columns 
data[names != 'Joe']=7
data

In [50]:
#Fancy Indexing
arr=np.empty((8, 4))
for i in range(8):
    arr[i]=i
arr    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [51]:
#Select a subset of the rows in a particular order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [53]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [54]:
arr=np.arange(32).reshape((8,4 ))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
#Transposing Arrays and Swapping Axes
arr=np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
#Transpose
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [57]:
arr=np.random.randn(6,3)
arr

array([[ 1.34200867, -0.33947176,  0.23663042],
       [ 0.40831478,  1.48409167, -0.03061501],
       [-0.11541201, -1.25010864, -1.65696249],
       [ 1.62661049, -0.08408748, -0.74171325],
       [ 0.89524531,  0.46362794,  0.56273158],
       [-0.44658182, -0.41088985,  0.75385361]])

In [58]:
np.dot(arr.T, arr) #Matrix dot (product)

array([[ 5.62778935,  0.75645918, -0.54306017],
       [ 0.75645918,  4.27139282,  1.9591344 ],
       [-0.54306017,  1.9591344 ,  4.23755658]])

In [59]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [60]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

##Universal Functions

Universal Functions

In [61]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [63]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [64]:
x=np.random.randn(8)
y=np.random.randn(8)

In [65]:
x

array([-1.35264606,  0.40265636, -0.47052149, -0.86962332, -1.31624445,
       -0.58745902, -0.65644481, -0.48008886])

In [66]:
y

array([-0.59781637,  0.46408338,  1.66924403,  0.26884326,  0.05466004,
        1.21578975, -0.29476034,  0.98492689])

In [67]:
np.maximum(x, y)

array([-0.59781637,  0.46408338,  1.66924403,  0.26884326,  0.05466004,
        1.21578975, -0.29476034,  0.98492689])

In [68]:
arr=np.random.randn(7)*5
arr

array([ 5.46948003, -4.95488824,  0.85814347, -7.39550903,  2.54734799,
        0.53581001, -6.9314048 ])

In [69]:
remainder, whole_part=np.modf(arr)
remainder

array([ 0.46948003, -0.95488824,  0.85814347, -0.39550903,  0.54734799,
        0.53581001, -0.9314048 ])

In [70]:
whole_part

array([ 5., -4.,  0., -7.,  2.,  0., -6.])

In [71]:
np.sqrt(arr)

<ipython-input-71-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.33869195,        nan, 0.92636033,        nan, 1.59604135,
       0.73199044,        nan])

In [72]:
np.sqrt(arr, arr)

<ipython-input-72-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([2.33869195,        nan, 0.92636033,        nan, 1.59604135,
       0.73199044,        nan])

In [113]:
"""abs, fabs Compute the absolute value element-wise for integer, floating-point, or complex values
sqrt Compute the square root of each element (equivalent to arr ** 0.5)
square Compute the square of each element (equivalent to arr ** 2)
exp Compute the exponent ex of each element
log, log10,
log2, log1p
Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
sign Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)
ceil Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that
number)
floor Compute the floor of each element (i.e., the largest integer less than or equal to each element)
rint Round elements to the nearest integer, preserving the dtype
modf Return fractional and integral parts of array as a separate array
isnan Return boolean array indicating whether each value is NaN (Not a Number)
isfinite, isinf Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite,
respectively
cos, cosh, sin,
sinh, tan, tanh
Regular and hyperbolic trigonometric functions
arccos, arccosh,
arcsin, arcsinh,
arctan, arctanh
Inverse trigonometric functions
logical_not Compute truth value of not x element-wise (equivalent to ~arr).
"""

'abs, fabs Compute the absolute value element-wise for integer, floating-point, or complex values\nsqrt Compute the square root of each element (equivalent to arr ** 0.5)\nsquare Compute the square of each element (equivalent to arr ** 2)\nexp Compute the exponent ex of each element\nlog, log10,\nlog2, log1p\nNatural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively\nsign Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)\nceil Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that\nnumber)\nfloor Compute the floor of each element (i.e., the largest integer less than or equal to each element)\nrint Round elements to the nearest integer, preserving the dtype\nmodf Return fractional and integral parts of array as a separate array\nisnan Return boolean array indicating whether each value is NaN (Not a Number)\nisfinite, isinf Return boolean array indicating whether each element is finite (non-inf, non-N

In [114]:
#add Add corresponding elements in arrays
#subtract Subtract elements in second array from first array
#multiply Multiply array elements
#divide, floor_divide Divide or floor divide (truncating the remainder)
#power Raise elements in first array to powers indicated in second array
#maximum, fmax Element-wise maximum; fmax ignores NaN
#minimum, fmin Element-wise minimum; fmin ignores NaN
#mod Element-wise modulus (remainder of division)
#copysign Copy sign of values in second argument to values in first argument

## Array-Oriented Programming with Arrays

In [138]:
points=np.arange(-5, 5, 0.01)

In [74]:
xs, ys=np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [76]:
z=np.sqrt(xs**2+ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [77]:
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond=np.array([True, False, True, True, False])
result=[(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [78]:
result=np.where(cond, xarr, yarr)

In [79]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [80]:
arr=np.random.randn(4,4)
arr

array([[ 0.22363772, -0.13360319, -0.90021051,  0.65935632],
       [ 0.69888461, -1.30062094, -1.13932629, -0.46638486],
       [ 1.3083772 , -0.50953496,  0.37324846, -1.42621896],
       [ 0.75073353, -1.86898482, -0.66515797, -0.49801132]])

In [81]:
arr>0

array([[ True, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

In [82]:
np.where(arr>0, 2, -2)

array([[ 2, -2, -2,  2],
       [ 2, -2, -2, -2],
       [ 2, -2,  2, -2],
       [ 2, -2, -2, -2]])

In [83]:
#Combination of scalar and array can be used with where
np.where(arr>0,2, arr)

array([[ 2.        , -0.13360319, -0.90021051,  2.        ],
       [ 2.        , -1.30062094, -1.13932629, -0.46638486],
       [ 2.        , -0.50953496,  2.        , -1.42621896],
       [ 2.        , -1.86898482, -0.66515797, -0.49801132]])

## Mathematical and Statiscal Methods

In [84]:
arr=np.random.randn(5, 4)
arr

array([[ 3.06657341e-01,  1.69985641e-04, -9.53129612e-01,
        -1.28615863e+00],
       [-9.32478100e-01, -5.78687111e-01,  5.24963498e-01,
        -2.35826996e-01],
       [-2.58891129e-01, -2.48021788e-01,  2.18381338e-02,
        -6.78148512e-01],
       [ 6.27788296e-02, -5.40183056e-03, -1.11668402e+00,
         1.22521008e+00],
       [-3.83543345e-01,  5.41661532e-01, -6.36198411e-01,
         6.61981127e-01]])

In [85]:
arr.mean()#or arr.mean(arr)

-0.19839544801650824

In [86]:
arr.sum()

-3.9679089603301647

In [87]:
#arr.mean(1) means accross the columns
#arr.sum(0) means accross the rows

In [88]:
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [89]:
arr=np.array([[0,1,2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [91]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [112]:
#sum Sum of all the elements in the array or along an axis; zero-length arrays have sum 0
#mean Arithmetic mean; zero-length arrays have NaN mean
#std, var Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default
#denominator n)
#min, max Minimum and maximum
#argmin, argmax Indices of minimum and maximum elements, respectively
#cumsum Cumulative sum of elements starting from 0
#cumprod Cumulative product of elements starting from 1

## Methods for Boolean Arrays

In [92]:
arr=np.random.randn(100)
(arr>0).sum()

47

In [95]:
bools=np.array([False, False, True, False])

In [96]:
#any tests whether at least one value in an arrays is True
#all checks if every value is True
bools.any()

True

In [97]:
bools.all()

False

## Sorting

In [98]:
arr=np.random.randn(6)
arr

array([-1.02934298,  1.28514793,  1.69985525, -1.92614165,  0.48740195,
       -1.38721989])

In [102]:
arr.sort()
arr

array([-1.92614165, -1.38721989, -1.02934298,  0.48740195,  1.28514793,
        1.69985525])

In [103]:
arr=np.random.randn(5, 3)
arr

array([[-1.27443471,  1.41692767, -0.95011109],
       [ 1.98873472, -1.7035329 , -0.57631117],
       [-0.20173639,  0.04349786, -0.30000264],
       [ 0.44097388, -1.18636478,  0.09658416],
       [-0.28821246, -0.22170336,  0.4248901 ]])

In [105]:
arr.sort(1)
arr

array([[-1.27443471, -0.95011109,  1.41692767],
       [-1.7035329 , -0.57631117,  1.98873472],
       [-0.30000264, -0.20173639,  0.04349786],
       [-1.18636478,  0.09658416,  0.44097388],
       [-0.28821246, -0.22170336,  0.4248901 ]])

In [106]:
large_arr=np.random.randn(1000)
large_arr.sort()

In [108]:
#np.sort returns a sorted copy of an array
large_arr[int(0.05*len(large_arr))] #5% quantile
#computing the quantiles of an array

-1.6589615061002354

## Unique and Other Set Logic

In [109]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [110]:
ints=np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [111]:
#unique(x) Compute the sorted, unique elements in x
#intersect1d(x, y) Compute the sorted, common elements in x and y
#union1d(x, y) Compute the sorted union of elements
#in1d(x, y) Compute a boolean array indicating whether each element of x is contained in y
#setdiff1d(x, y) Set difference, elements in x that are not in y
#setxor1d(x, y) Set symmetric differences; elements that are in either of the arrays, but not both

## File Input and Output with Arrays

In [115]:
arr=np.arange(10)
np.save('some_array', arr) #arrays are saved by default in an uncompressed raw binary format with file extension .npy

In [118]:
np.load('some_array.npy') #load the saved array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.savez('array_archive.npz', a=arr, b=arr)#saving multiple arrays in an uncompressed archive np.savez 

## Linear Algebra

In [120]:
x=np.array([[1., 2., 3.], [4., 5., 6.]])
y=np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [121]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [122]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [123]:
#x.dot(y) is equivalent to np.dot(x, y)

In [124]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [125]:
from numpy.linalg import inv, qr

In [126]:
x=np.random.randn(5, 5)

In [129]:
x

array([[-0.35853448, -1.29287217, -0.30717688, -0.48004175,  0.58772835],
       [-0.51375775, -0.90018865, -0.30277298, -0.47344863,  1.76740266],
       [ 0.206045  , -0.20513462, -2.0268451 ,  0.47577352,  0.00793924],
       [-0.75631312,  0.84478052, -0.53401149, -0.40196541,  0.02711898],
       [ 0.56042358,  1.98829419, -0.94166344,  2.14483078,  1.36565908]])

In [127]:
mat=x.T.dot(x)

In [128]:
mat

array([[ 1.32103267,  1.35911954, -0.27578632,  2.01940564, -0.37226474],
       [ 1.35911954,  7.19090618, -1.2379571 ,  4.87421012,  0.38575955],
       [-0.27578632, -1.2379571 ,  5.4660285 , -2.47856864, -2.03222301],
       [ 2.01940564,  4.87421012, -2.47856864,  5.4428294 ,  1.8030755 ],
       [-0.37226474,  0.38575955, -2.03222301,  1.8030755 ,  5.33495996]])

In [130]:
inv(mat)

array([[ 19.09667678,   6.23141912,  -2.82318683, -15.63810508,
          5.09179619],
       [  6.23141912,   2.45064418,  -0.99038557,  -5.53803073,
          1.75206214],
       [ -2.82318683,  -0.99038557,   0.67711055,   2.47604002,
         -0.70429201],
       [-15.63810508,  -5.53803073,   2.47604002,  13.50076197,
         -4.31047179],
       [  5.09179619,   1.75206214,  -0.70429201,  -4.31047179,
          1.60459482]])

In [131]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.21964677e-15, -5.55111512e-17,
        -8.88178420e-15,  5.55111512e-16],
       [-8.65973959e-15,  1.00000000e+00, -5.55111512e-16,
        -2.22044605e-14, -2.44249065e-15],
       [-3.55271368e-15, -8.88178420e-16,  1.00000000e+00,
         7.10542736e-15,  4.44089210e-16],
       [ 3.55271368e-15,  1.33226763e-15,  6.66133815e-16,
         1.00000000e+00, -4.44089210e-16],
       [ 0.00000000e+00, -1.77635684e-15,  0.00000000e+00,
         3.55271368e-15,  1.00000000e+00]])

In [132]:
q,r=qr(mat)

In [133]:
r

array([[-2.80801914, -7.69565864,  2.77883464, -7.22785291, -0.80060072],
       [ 0.        , -4.44662211,  1.69198542, -2.80323394, -2.12953651],
       [ 0.        ,  0.        , -5.58341828,  2.23260241,  3.75505991],
       [ 0.        ,  0.        ,  0.        , -1.33049138, -4.10293726],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.14051511]])

In [134]:
q

array([[-0.47045002,  0.50854406, -0.03063847, -0.08495624,  0.71547428],
       [-0.48401363, -0.77949113, -0.25538555,  0.17970113,  0.2461912 ],
       [ 0.09821383,  0.10842769, -0.89723717, -0.40468399, -0.09896367],
       [-0.71915665,  0.1484664 ,  0.13098682, -0.27705213, -0.6056864 ],
       [ 0.13257201, -0.31619248,  0.33413682, -0.84850629,  0.22546981]])

In [135]:
#diag Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a
#square matrix with zeros on the off-diagonal
#dot Matrix multiplication
#trace Compute the sum of the diagonal elements
#det Compute the matrix determinant
#eig Compute the eigenvalues and eigenvectors of a square matrix
#inv Compute the inverse of a square matrix
#pinv Compute the Moore-Penrose pseudo-inverse of a matrix
#qr Compute the QR decomposition
#svd Compute the singular value decomposition (SVD)
#solve Solve the linear system Ax = b for x, where A is a square matrix
#lstsq Compute the least-squares solution to Ax = b

## Pseudorandom Number Generation

In [136]:
samples=np.random.normal(size=(4, 4))
samples

array([[ 0.79916758, -0.88151534,  0.74898275, -1.70769619],
       [ 0.39691601,  0.76479763, -0.29060552,  1.40408179],
       [ 1.40220482,  0.51442124,  0.21639461,  0.31063719],
       [ 0.42894956,  2.3072271 ,  0.0795415 ,  1.33225187]])

In [137]:
#seed Seed the random number generator
#permutation Return a random permutation of a sequence, or return a permuted range
#shuffle Randomly permute a sequence in-place
#rand Draw samples from a uniform distribution
#randint Draw random integers from a given low-to-high range
#randn Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)
#binomial Draw samples from a binomial distribution
#normal Draw samples from a normal (Gaussian) distribution
#beta Draw samples from a beta distribution
#chisquare Draw samples from a chi-square distribution
#gamma Draw samples from a gamma distribution
#uniform Draw samples from a uniform [0, 1) distribution